"""The participant documents, generated from the code.

The problem statement carries the task, the semantics and the behavioural warnings;
**every number** -- dtypes, shapes, ranges, palette values, beam counts, limits -- lives in
the kit's schema document and its example dumps. A document that restates numbers by hand
drifts from the code that produces them, so this module *is* the document: `usvnav docs`
writes `docs/` from the same constants and the same observation loop the scorer runs, and
`usvnav docs --check` reports any committed file that differs from what the code generates.

What is written:

    docs/OBSERVATION.md     the observation and action schema
    docs/examples/          one course, its reset metadata, and one observation per
                            condition, captured from `sim.run_episode`
    docs/RULES.md           the capability list, the interface, how the kit runs a submission;
                            contest rules are on the site, not here
    docs/RUNTIME.md         what a submission meets at scoring time
    docs/PACKAGING.md       the submission directory, its manifest, and every check the
                            local validator applies

The prose is here rather than in Markdown files because the prose *names the numbers*:
"180 beams" is a sentence in which 180 is `lidar.N_BEAMS`, and a sentence that carries a
value has to be built where the value is. Semantics that are not numbers -- why no-return
is the maximum range rather than zero -- are repeated from the statement deliberately,
because an agent built on the wrong reading is structurally wrong.
"""

from __future__ import annotations

import json
import pathlib

import numpy as np

from . import __version__, coursefile, plant, runtime
from . import look as _look
from .contest import CLEARANCE_PERCENTILE, D_CAP
from .runner import CONSTRUCT_TIMEOUT_S
from .lanerules import LANE_TURN_MAX_DEG
from .lidar import MAX_RANGE, N_BEAMS
from .objects import CAPACITY, CIRCLE, CLASSES, RECT
from .rules import LEG_MAX, LEG_MIN, RADIUS_GOAL, RADIUS_INTERMEDIATE, WP_MAX, WP_MIN
from .png import write_png
from .render import COLOUR_OF, PALETTE_TRACK1, TRACK1
from .sim import (EPISODE_TIME_LIMIT_S, NAVIGATIONAL, SENSING_RANGE, SUBMISSION_FAULT, TICK_LIMIT,
                  run_episode)
from .submission import CHECKS, FORMAT, MANIFEST, REQUIRED, SIZE_CAP_BYTES
from .world import (A_MAX, BANK, BUOY, DOCK, EGO, EGO_SLOT, LANE_CLEAR, MOORED, MOVING, OUTSIDE_WORLD, PIER, SIZE_RANGES, STATIC_CLASSES, TRAFFIC_SPEED_MAX, TRAFFIC_SPEED_MIN, UNOBSERVED, V_WAIT, WATER)

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

#: The example dumps come from the course committed beside them, `docs/examples/course.json`;
#: it has moving vessels in it so the 1-1 list shows a non-zero velocity. The tutorial agent
#: drives to this tick under each condition; `DUMP_SEED` is the 1-4 disturbance seed.
DUMP_SEED = 4250
DUMP_TICK = 120

CONDITIONS = ("1-1", "1-2", "1-3", "1-4")

#: Contest rules live on the site, not in the kit (owner, 2026-10-02): every document that
#: would otherwise touch one carries this pointer instead.
SITE_RULES = ("Contest rules — limits, scoring, ranking, what is published, the deadline — are on "
              "the site's problem page and common rules "
              "(https://kraftonai-autonomy-hackathon.com/problems/), which are authoritative.")

STAMP = f"*Generated by `usvnav docs` from usvnav {__version__}. Do not edit; edit the code.*"


# --------------------------------------------------------------------------- capture

def _course():
    path = DOCS / "examples" / "course.json"
    if not path.is_file():                               # pragma: no cover
        raise RuntimeError(f"{path} is missing; it ships with the kit")
    return coursefile.load(path)


def capture(course, condition: str, tick: int = DUMP_TICK):
    """`(meta, obs)` at `tick`, from the scoring loop itself."""
    from .agent import TutorialAgent

    got = {}

    def hook(t, meta, obs):
        if t == tick:
            got["meta"], got["obs"] = meta, obs

    res = run_episode(course, TutorialAgent(), condition=condition, seed=DUMP_SEED,
                      tick_limit=tick + 1, on_observation=hook)
    if "obs" not in got:                                 # pragma: no cover
        raise RuntimeError(f"the episode ended as {res.outcome} at {res.ticks} < {tick}")
    return got["meta"], got["obs"]


def _listify(v):
    if isinstance(v, dict):
        return {k: _listify(x) for k, x in v.items()}
    if isinstance(v, np.ndarray):
        return np.round(v, 4).tolist() if v.dtype.kind == "f" else v.tolist()
    if isinstance(v, (np.generic,)):
        return v.item()
    if isinstance(v, (list, tuple)):
        return [_listify(x) for x in v]
    return v


def _shape(v):
    a = np.asarray(v)
    return f"`{a.dtype}`", ("scalar" if a.shape == () else "×".join(str(n) for n in a.shape))


# --------------------------------------------------------------------------- helpers

def _table(head, rows):
    out = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return out


def _hex(rgb):
    return "#%02X%02X%02X" % tuple(rgb)


def _fmt(v, nd=3):
    a = np.asarray(v)
    if a.shape == ():
        return f"{a.item():.{nd}f}" if a.dtype.kind == "f" else str(a.item())
    return "[" + ", ".join(f"{x:.{nd}f}" if a.dtype.kind == "f" else str(x)
                           for x in a.reshape(-1)[:6]) + (", …" if a.size > 6 else "") + "]"


# --------------------------------------------------------------------------- OBSERVATION.md

def observation_md(course, captures: dict) -> str:
    meta, obs11 = captures["1-1"]
    obs12, obs13, obs14 = captures["1-2"][1], captures["1-3"][1], captures["1-4"][1]
    ol, img, scan = obs11["perception"], obs12["perception"], obs13["perception"]
    L = []
    a = L.append

    a("# Track 1 — observation and action schema")
    a("")
    a(STAMP)
    a("")
    a("This is where the numbers live. The problem statement carries the task, the meaning "
      "of each field and the warnings that change how an agent is designed; this document "
      "carries every dtype, shape, range, sentinel and constant, and `docs/examples/` "
      "carries one real observation per condition captured from the scoring loop. If a "
      "number here disagrees with the statement, this document is right.")
    a("")
    a("The interface, in full:")
    a("")
    a("```python")
    a("class Agent:")
    a("    def __init__(self, config_path): ...      # once per process; a path inside your submission")
    a("    def reset(self, meta): ...                # once per episode; clear all state here")
    a("    def act(self, obs) -> [v_cmd, w_cmd]: ... # every tick, 10 Hz simulated time")
    a("```")
    a("")
    a("No state may carry from one episode to the next; `reset` is where it is cleared. "
      "There is no end-of-episode callback: scoring learns nothing, so there is nothing to "
      "tell you.")
    a("")

    # ---- conventions
    a("## 1. Units, frames and signs")
    a("")
    a("SI units throughout: metres, seconds, radians. Every angle in every array is in "
      "radians and wrapped to (−π, π].")
    a("")
    a("**World frame:** right-handed 2D, `+x` along the reach's long axis, `+y` 90° "
      "counter-clockwise from it; heading ψ is measured counter-clockwise from `+x` to "
      "the bow.")
    a("")
    a("**Body frame:** origin at the hull rectangle's centre, `+x` through the bow, `+y` to "
      "**port**. A positive `w_cmd`, a positive yaw rate, a positive bearing and a LiDAR "
      "beam index increasing from the bow all mean the same direction: **to port, "
      "counter-clockwise seen from above**. Under this convention \"obstacle at beam 30 → "
      "bearing +60° → steer positive\" turns *toward* it, which is the trap the convention "
      "exists to make visible.")
    a("")
    a(f"**Raster mapping** (`bow_up`): a body-frame point `(x_b, y_b)` lands at "
      f"`row = {TRACK1.origin_px:.1f} − x_b / {TRACK1.m_per_px}`, "
      f"`col = {TRACK1.origin_px:.1f} − y_b / {TRACK1.m_per_px}` in continuous pixel "
      f"coordinates, so the hull centre sits on the corner shared by the four central "
      f"pixels, the bow points to row 0, and port is to the *left* of the image (a point "
      f"10 m ahead and 10 m to port lands upper-left).")
    a("")

    # ---- reset metadata
    a("## 2. Episode start — `reset(meta)`")
    a("")
    a("`meta` is a dict. It is identical in all four conditions and carries **no obstacle "
      "geometry**: perceiving the surroundings is the task.")
    a("")
    wps = np.asarray(meta["waypoints"])
    radii = np.asarray(meta["arrival_radii"])
    L += _table(("key", "type", "example", "meaning"), [
        ("`boundary`", f"`float64` N×2 (here N = {len(meta['boundary'])})",
         f"`{_fmt(np.asarray(meta['boundary'])[0], 2)}` …",
         "the navigable polygon in world metres — the shoreline. Water inside, bank "
         "outside; any part of the hull crossing it ends the episode as `out_of_bounds`"),
        ("`waypoints`", f"`float64` K×2 (here K = {len(wps)})", f"`{_fmt(wps[0], 2)}` …",
         "the full ordered chain in world metres, to be reached **in order**"),
        ("`arrival_radii`", f"`float64` K", f"`{_fmt(radii, 1)}`",
         f"metres; reaching waypoint k means the hull **centre** comes within radius k. "
         f"Intermediate waypoints {radii[0]:.0f} m, the goal {radii[-1]:.0f} m"),
        ("`hull`", "`(float, float)`", f"`{tuple(meta['hull'])}`",
         f"length and width in metres. **A constant** — {plant.HULL_LENGTH} × "
         f"{plant.HULL_WIDTH} m in every episode and every condition; it is listed for "
         f"completeness, not because it varies"),
        ("`observation_mode`", "`str`", f"`{meta['observation_mode']!r}`",
         "one of `1-1`, `1-2`, `1-3`, `1-4`; fixed for the episode and decides the type "
         "of `obs[\"perception\"]`"),
    ])
    a("")
    a(f"The start is stationary, at the departure berth, heading aligned with the first leg "
      f"plus a per-episode offset of up to ±30°. Courses have {WP_MIN}–{WP_MAX} waypoints on legs "
      f"of {LEG_MIN:g}–{LEG_MAX:g} m; a course may run down the reach and back, with its goal "
      f"beside its start.")
    a("")

    # ---- action
    a("## 3. The action — `act(obs) -> [v_cmd, w_cmd]`")
    a("")
    a("Two numbers, in any array-like of length 2: a **surge setpoint** in m/s and a "
      "**yaw-rate setpoint** in rad/s. They are setpoints, not forces: an autopilot turns them "
      "into thrust for the vessel, which is **Track 2's public nominal model** (`usvnav/plant.py`: "
      "a planar rigid body with linear damping, a stern azimuth thruster and a bow thruster). "
      "The hull has inertia and slips: a turn pushes the stern sideways, a hard turn at speed "
      "bleeds speed because the stern thruster's thrust is shared between surge and turning, "
      "the yaw rate you can have falls as speed rises, and a lower speed setpoint throttles back "
      "and coasts rather than braking — only a negative `v_cmd` reverses.")
    a("")
    L += _table(("quantity", "value"), [
        ("`v_cmd` range", f"[{plant.V_MIN}, {plant.V_MAX}] m/s; cruise {plant.V_CRUISE} m/s"),
        ("`w_cmd` range", f"[−{plant.W_MAX}, {plant.W_MAX}] rad/s"),
        ("slew limits, applied by the simulator", f"{plant.SLEW_V} m/s and {plant.SLEW_W} rad/s per tick"),
        ("vessel", f"{plant.MASS:.0f} kg, damping X_u {plant.X_U:.0f} / Y_v {plant.Y_V:.0f} N·s/m, "
                   f"N_r {plant.N_R:.0f} N·m·s; stern {plant.K_STERN:.0f} N (reverse {100 * plant.REVERSE_MAX:.0f} %), "
                   f"bow {plant.K_BOW:.0f} N, arm {plant.ARM} m"),
        ("what a hard turn at full speed does", "about 1.6 m/s and 0.5 rad/s, the hull slipping ~10°"),
        ("control period", f"{plant.DT} s (10 Hz), simulated — the runner waits for `act`"),
        ("out-of-range but finite", "clipped to the range; the episode continues; "
                                    "`prev_action` shows the clipped value next tick"),
        ("NaN, ±inf, wrong shape, exception", "ends the episode as `invalid_action` / `crash`, "
                                              "a submission fault"),
    ])
    a("")
    a("The 1-4 disturbance enters as a **lateral drift with no yaw moment**, so turn "
      "authority is untouched by it; holding a straight course at cruise against the "
      "maximum drift needs about a 13° crab angle.")
    a("")

    # ---- common fields
    a("## 4. Common observation fields")
    a("")
    a("`obs` is a dict of named numpy arrays — never a flat vector. These six keys are "
      "present, with these types, in every condition. Real values are `float32`; the "
      "simulator integrates in `float64` and rounds on emission.")
    a("")
    meanings = {
        "t": "control tick since `reset`, 0-based; the time limit (§6) is in the same unit",
        "pose": "`x, y` in world metres and heading ψ in radians, wrapped — your GNSS and compass",
        "vel": "surge `u`, sway `v` (m/s, **over ground, body axes**) and yaw rate `r` (rad/s). "
               "`v` is the hull's slip: nonzero whenever it turns, in every condition, and under 1-4 "
               "it also carries the disturbance",
        "wp_index": "index into `meta[\"waypoints\"]` of the waypoint you are heading for now",
        "wp_polar": "distance in metres and **bow-relative bearing** in radians to that waypoint, "
                    "wrapped; positive is to port. Redundant with `pose` and supplied so nobody "
                    "re-implements the wrap",
        "prev_action": "the command **actually applied** last tick — after clipping — which can "
                       "differ from what you returned. `[0, 0]` at `t = 0`",
    }
    rows = []
    for k in ("t", "pose", "vel", "wp_index", "wp_polar", "prev_action"):
        dt, sh = _shape(obs14[k])
        rows.append((f"`{k}`", dt, sh, f"`{_fmt(obs14[k])}`", meanings[k]))
    L += _table(("field", "dtype", "shape", "example (1-4, tick %d)" % DUMP_TICK, "meaning"), rows)
    a("")
    a("Deliberately absent: obstacle information of any kind (that is `perception`), the "
      "disturbance state, remaining time (compute it from `t`), and any success or failure "
      "flag.")
    a("")

    # ---- perception
    a("## 5. `obs[\"perception\"]`, per condition")
    a("")
    a(f"Sensing range is {SENSING_RANGE:.0f} m. For 1-3 that is a radius; for 1-1, "
      f"1-2 and 1-4 it is the half-width of a {2 * SENSING_RANGE:.0f} × {2 * SENSING_RANGE:.0f} m "
      f"square centred on the hull, which reaches {TRACK1.reach_m:.2f} m into its corners. "
      f"Every observation is exact: no sensor noise, and the scoring renderer adds no noise "
      f"(renderer noise exists only as an option you switch on yourself in the studio or with "
      f"`--noise`, see 5.2).")
    a("")

    # 1-1
    a("### 5.1 Condition 1-1 — structured object list")
    a("")
    a(f"A dict of fixed-length arrays with a validity mask, capacity {CAPACITY}, rows "
      f"**nearest first**, zero-padded. A body is listed when its footprint intersects the "
      f"observation square. Occluded bodies are listed — there is no visibility test.")
    a("")
    rows = []
    desc = {
        "valid": "row `i` is a body; rows after the last valid one are zero padding",
        "cls": "object class id, table below",
        "primitive": f"{CIRCLE} = circle, {RECT} = oriented rectangle",
        "pos": "body centre in the **body frame**, metres: `+x` ahead, `+y` to port",
        "heading": "the body's heading relative to yours, radians, wrapped (0 for a circle)",
        "vel": "the body's **over-ground** velocity, components in **your** axes, m/s. Static "
               "bodies are exactly `[0, 0]`; subtract your own `vel[:2]` for relative velocity",
        "extent": "`(length, width)` in metres; a circle carries `(diameter, diameter)`",
    }
    for k in ("valid", "cls", "primitive", "pos", "heading", "vel", "extent"):
        dt, sh = _shape(ol[k])
        rows.append((f"`{k}`", dt, sh, desc[k]))
    L += _table(("key", "dtype", "shape", "meaning"), rows)
    a("")
    rows = []
    for i, cls in enumerate(CLASSES):
        prim = "circle" if cls == BUOY else "rectangle"
        sr = SIZE_RANGES[cls]
        size = (f"{sr[0]} m diameter, fixed" if cls == BUOY
                else f"{sr[0][0]:g}–{sr[0][1]:g} m × {sr[1][0]:g}–{sr[1][1]:g} m")
        moves = ("yes, on a **lane** — a fixed path between two berths or end caps, run on a schedule "
                 "(open lanes: one vessel every headway; closed lanes circulate) at %.1f–%.1f m/s, a pure "
                 "function of time (§9); it does not react to you"
                 % (TRAFFIC_SPEED_MIN, TRAFFIC_SPEED_MAX) if cls == MOVING else "no")
        rows.append((i, f"`{cls}`", prim, size, moves))
    L += _table(("`cls`", "class", "primitive", "size", "moves"), rows)
    a("")
    n_valid = int(ol["valid"].sum())
    a(f"**The bank is not in the list**. `meta[\"boundary\"]` already gives the "
      f"shoreline exactly, so a row for it would carry nothing — but it means an agent "
      f"driving on the object list alone drives ashore unless it puts the boundary in "
      f"itself. 1-3's ray cast hits the bank and 1-2 draws it; 1-1 does not contain it. "
      f"The example dump has {n_valid} valid rows.")
    a("")

    # 1-2
    a("### 5.2 Condition 1-2 — top-view picture")
    a("")
    dt, sh = _shape(img)
    a(f"A {dt} array of shape {sh}: rows × columns × RGB, {TRACK1.m_per_px} m per pixel, "
      f"{TRACK1.size_px * TRACK1.m_per_px:.0f} m across, `bow_up` — the bow points to row 0 "
      f"and the whole scene rotates with you, so consecutive frames are mutually rotated by "
      f"your yaw and `vel[2]` is what pays for compensating that. The ego hull is "
      f"drawn. **Nothing occludes anything**: every body inside the square is drawn whole, "
      f"whatever stands in front of it.")
    a("")
    a("**The raster is the studio's picture.** It is drawn by the same code that draws the map "
      "in `usvnav studio` and `usvnav view` (`usvnav/look.py`), so what "
      "you see there is what the agent receives — not a flat class map. The base colours, exact "
      "sRGB:")
    a("")
    appears = {UNOBSERVED: "no — it has no source in Track 1",
               WATER: "yes", DOCK: "yes", PIER: "yes (also rocks)",
               BANK: "yes — outside the boundary polygon", "vessel": "yes — moored **and** moving "
               "vessels share it; telling them apart is 1-2's task, not the palette's",
               EGO: "yes — your own hull", BUOY: "yes"}
    rows = [(f"`{name}`", _hex(rgb), str(tuple(rgb)), appears[name])
            for name, rgb in PALETTE_TRACK1.items()]
    L += _table(("class", "hex", "RGB", "appears in a 1-2 raster?"), rows)
    a("")
    a(f"`{OUTSIDE_WORLD}` is in the shared ten-class vocabulary and has **no colour** here: "
      f"generated terrain extends past the raster's {TRACK1.reach_m:.2f} m corner reach, so "
      f"it can never be painted; if it ever had to be, the renderer raises rather "
      f"than substituting.")
    a("")
    a("**What is drawn on top of the base colours**, all of it deterministic and stated in "
      f"metres (`usvnav/look.py`): a wet band {_look.WATERLINE_M} m into the bank and a shallow "
      f"band {_look.SHALLOW_M} m into the water along every shoreline; a drop shadow "
      f"{_look.SHADOW_M} m down-right of every body; a lighter deck panel inset "
      f"{_look.DECK_INSET_M} m on piers, vessels and docks; and an outline "
      f"{_look.OUTLINE_M} m thick around every body in a darker tone (a ring outside the "
      f"footprint for buoys and your own hull). The picture is painted at "
      f"{TRACK1.m_per_px / TRACK1.subsamples} m/px and box-downsampled {TRACK1.subsamples}× to "
      f"{TRACK1.m_per_px} m/px, so edges are anti-aliased. Inside a class the colour "
      "is flat: the base colour exactly. Segment it as you would any picture — the base colours "
      "are the anchors; expect outline, shadow, shoreline and anti-aliased edge tones that are "
      "not in the table. `usvnav observe` writes the frame at any tick; the studio shows it "
      "beside the map it was drawn from.")
    a("")
    a("**Noise is yours to add.** The scorer renders with no noise at all: the "
      "picture above is what a submission is scored on. Renderer noise is an exercise you set "
      "yourself — Track 2's renders carry noise; here the tooling lets you add your own and "
      "test against it. A noise function has the shape `(class_name, x_world, y_world) -> "
      "offsets`: the class being painted, the world coordinates of every pixel centre in "
      "metres, and integer offsets added to that class's base colour. Hand it to "
      "`RasterConfig.noise`, to `usvnav run|observe|view --noise module:function`, or pick it in "
      "the studio's *noise* selector, which applies it to every run the studio starts and to "
      "*What the agent saw*; the studio's work folder gets a `noise.py` to write them in. The "
      "kit ships one example, `usvnav.look.grain` (`--noise grain`): value noise of "
      + ", ".join(f"±{a_} levels in {b_} m blocks on {n}" for n, (b_, a_) in _look.GRAIN_EXAMPLE.items() if n != OUTSIDE_WORLD)
      + ", anchored to the world so it moves with the scene.")
    a("")
    a(f"Bodies smaller than {TRACK1.min_marker_px:.1f} px are drawn at {TRACK1.min_marker_px:.1f} px"
      f", so a {SIZE_RANGES[BUOY][0]} m buoy paints as "
      f"{TRACK1.min_marker_px * TRACK1.m_per_px:.1f} m and is never missing, while collision and "
      f"the 1-1 list keep its true size: a conservative agent gives it "
      f"{(TRACK1.min_marker_px * TRACK1.m_per_px - SIZE_RANGES[BUOY][0]) / 2:.1f} m more room "
      f"than it needs.")
    a("")
    a("A rule-based classifier is enough for this picture — the classes are a handful of "
      "known colours, drawn without noise — and what 1-2 is testing is what comes "
      "after: objects carry no velocity and no identity, so a moving vessel is found by "
      "**associating it across frames** that your own rotation has moved, at about 0.3–0.5 px "
      "per tick.")
    a("")
    counts = {}
    flat = img.reshape(-1, 3)
    for name, rgb in PALETTE_TRACK1.items():
        counts[name] = int(np.all(flat == np.array(rgb, dtype=np.uint8), axis=1).sum())
    other = int(len(flat) - sum(counts.values()))
    a(f"In the example dump, pixels carrying a base colour exactly: "
      + ", ".join(f"`{k}` {v}" for k, v in counts.items() if v)
      + f"; the other {other} of {len(flat)} carry shoreline, shadow, deck, outline or "
      f"anti-aliased edge tones.")
    a("")

    # 1-3
    a("### 5.3 Condition 1-3 — planar LiDAR")
    a("")
    dt, sh = _shape(scan)
    a(f"A {dt} array of {sh} ranges in metres. Beam `i` points at bearing "
      f"`i · 2π/{N_BEAMS}` rad from the bow, **increasing to port** — {360 / N_BEAMS:.0f}° "
      f"spacing over the full 360°, so beam {N_BEAMS // 4} is abeam to port and beam "
      f"{3 * N_BEAMS // 4} to starboard. First return only, so **this is the one condition "
      f"with occlusion**: a body behind another is not reported. Single planar cast, no "
      f"mount height — the world has no vertical dimension.")
    a("")
    a(f"**No return is `{MAX_RANGE:.1f}`, the maximum range — never `0`.** A zero would be "
      f"indistinguishable from a surface at zero distance, and any agent that judges danger "
      f"by the array's minimum would read open water as an imminent collision. The bank "
      f"returns beams like any surface.")
    a("")
    a(f"Example dump: min {scan.min():.2f} m at beam {int(scan.argmin())}, "
      f"{int((scan >= MAX_RANGE).sum())} of {N_BEAMS} beams with no return.")
    a("")

    # 1-4
    a("### 5.4 Condition 1-4 — the raster, under a disturbance")
    a("")
    a(f"`perception` is exactly 1-2's raster. What changes is the plant: an "
      f"Ornstein–Uhlenbeck drift in the **world frame** with correlation time "
      f"τ = {plant.OUDisturbance.TAU:.0f} s, bounded so the induced lateral speed never "
      f"exceeds {plant.OUDisturbance.CAP} m/s. It is smooth and mean-reverting, changes "
      f"meaningfully over about τ — many times in one run — and is **not** in the observation: "
      f"you see it as the mismatch between heading and course, which is `vel[1]` — the sway "
      f"component, on top of the slip your own turns produce (which is there in every "
      f"condition). In the example dump at tick "
      f"{DUMP_TICK}, `vel` is `{_fmt(obs14['vel'])}` against `{_fmt(obs12['vel'])}` under "
      f"1-2 on the same course at the same tick.")
    a("")
    a("The generator (`usvnav.plant.OUDisturbance`) ships; hidden episodes use unseen seeds "
      "of the same family.")
    a("")

    # ---- outcomes
    a("## 6. How an episode ends, and the time limit")
    a("")
    L += _table(("outcome", "tier", "meaning"), [
        ("`goal`", "navigational", "every waypoint reached in order, the hull centre inside the "
                                   "goal radius on the last one"),
        ("`static_collision`", "navigational", "footprint intersection with a buoy, pier, moored "
                                               "vessel or dock, tested every tick"),
        ("`dynamic_collision`", "navigational", "footprint intersection with a moving vessel"),
        ("`out_of_bounds`", "navigational", "**any part** of the hull outside the boundary polygon "
                                            "— the shoreline; there is no separate grounding"),
        ("`timeout`", "navigational", "`t` reached the limit without a collision or leaving the "
                                      "boundary"),
        ("`crash`", "submission fault", "`reset` or `act` raised"),
        ("`invalid_action`", "submission fault", "a non-finite or malformed action"),
        ("`time_overrun`", "submission fault", f"the episode's wall-clock limit ran out — "
                                               f"{EPISODE_TIME_LIMIT_S:.0f} s from the `reset` call, "
                                               f"the agent's time and the scorer's together; or "
                                               f"`Agent(config_path)` past its time limit (RULES.md §4)"),
    ])
    a("")
    a(f"**Time limit: {TICK_LIMIT} ticks** ({TICK_LIMIT * plant.DT:.0f} s simulated), one "
      f"constant for every course. A run still afloat and untouched "
      f"at the limit ends as `timeout`; the run record keeps how many waypoints it reached.")
    a("")
    a("Within one tick the checks run in a fixed order so a re-run reproduces the outcome: "
      "submission fault → collision → out-of-bounds → goal → timeout.")
    a("")
    a(f"**Clearance**, as the simulator measures it: per tick, the minimum "
      f"surface-to-surface distance from the hull rectangle to any body **or the bank**, "
      f"capped at {D_CAP:.0f} m; the episode statistic is the mean of the lowest "
      f"{CLEARANCE_PERCENTILE:.0f}% of those per-tick minima. Open water you happened to "
      f"cross cannot raise it.")
    a("")

    # ---- courses
    a("## 7. What the courses contain")
    a("")
    a(f"A course is a stretch of river with a shoreline, a start pose, a chain of {WP_MIN}–{WP_MAX} "
      f"waypoints on legs of {LEG_MIN:g}–{LEG_MAX:g} m — across the width, and out and back "
      f"with the goal beside the start — static bodies of the classes in §5.1 with the "
      "sizes given there, and moving vessels on lanes (§9). The world is a 400 × 150 m "
      "box; the channel is 40–120 m wide. What an agent has to handle is the capability list "
      "in `docs/RULES.md` §1; no passage on a hidden route is narrower than %g m, two hull "
      "widths." % (2.0 * plant.HULL_WIDTH))
    a("")
    a("The practice courses in `sets/practice/` are a few composite courses of low-to-medium "
      "difficulty. They show the format and the feel of a course, not the range of what "
      "the hidden set contains; the courses you test against are the ones you author in the "
      "editor or write as files (§9). Every hidden course passes the same course-file rules the studio and `usvnav validate` "
      "apply. No competent agent is distributed; the shipped tutorial agent usually fails.")
    a("")

    # ---- dumps
    a("## 8. The example dumps (`docs/examples/`)")
    a("")
    a(f"One course (`course.json`), its `meta.json`, and the observation at tick {DUMP_TICK} "
      f"under each condition, driven there by the shipped tutorial agent and captured from "
      f"`sim.run_episode` itself:")
    a("")
    a("- `observation-1-1.json` — the six common fields and the full object list, padding included;")
    a("- `observation-1-2.png` — the raster, pixel-exact (open it with any image library; "
      "the `-x3` copy is upscaled by nearest neighbour for looking at); "
      "`observation-1-2.json` — the common fields and the per-class pixel counts;")
    a("- `observation-1-3.json` — the common fields and the 180 ranges;")
    a("- `observation-1-4.json` / `.png` — the same, under the disturbance: compare `vel` "
      "and `pose` with 1-2's.")
    a("")
    a("Regenerate everything with `usvnav docs`; `usvnav observe COURSE --condition C` "
      "writes a single tick of your own.")
    a("")
    _course_file_section(a)
    return "\n".join(L)


def _course_file_section(a):
    """§9 of OBSERVATION.md: the course file, so anyone can write a course by hand — lanes
    included. Format and rules only; nothing about how the hidden courses are composed."""
    (l_lo, l_hi), (w_lo, w_hi) = SIZE_RANGES[MOVING]
    a(f"## 9. The course file (`{coursefile.FORMAT}`)")
    a("")
    a("Everything the studio, `usvnav validate`, `usvnav run` and the scorer read is one JSON file; "
      "the practice courses and `docs/examples/course.json` are examples. Metres and radians, "
      "`+x` along the reach, `+y` to port; coordinates are written to four decimals, and the file — not "
      "the object that produced it — is what runs. The editor writes it, and you can write it yourself:")
    a("")
    a("```")
    a("{\"format\": \"%s\"," % coursefile.FORMAT)
    a(" \"world\": {\"boundary\": [[x, y], ...]},                 the navigable polygon; water at the box's x-edges is an end cap")
    a(" \"start\": {\"x\": .., \"y\": .., \"heading_rad\": ..},")
    a(" \"waypoints\": [{\"x\": .., \"y\": .., \"arrival_radius_m\": 5.0}, ..., {\"..\": .., \"arrival_radius_m\": 3.0}],")
    a(" \"bodies\": [{\"class\": \"buoy\", \"primitive\": \"circle\", \"x\": .., \"y\": .., \"diameter_m\": 0.6},")
    a("            {\"class\": \"pier\" | \"moored_vessel\" | \"dock\", \"primitive\": \"rect\", \"x\": .., \"y\": .., \"length_m\": .., \"width_m\": .., \"heading_rad\": ..}],")
    a(" \"traffic\": [],                                            legacy closed loops (class, length_m, width_m, speed_mps, phase_m, route); lanes replace them")
    a(" \"lanes\": [{\"class\": \"moving_vessel\", \"closed\": false,")
    a("            \"route\": [[x0, y0], [x1, y1], ...],              the path, 2 or more points (a closed lane 3 or more)")
    a("            \"speeds_mps\": [v0, v1, ...],                      one speed per route point, linear in between")
    a("            \"headway_s\": 45.0, \"offset_s\": 0.0,             open lanes: a vessel enters at route[0] every headway_s seconds, shifted by offset_s")
    a("            \"vessels\": [{\"length_m\": 12, \"width_m\": 3}, ...]}]}  the sizes the vessels cycle through")
    a("```")
    a("")
    a(f"**Lanes** are how vessels move. An *open* lane's vessels appear at its first point on the schedule, run "
      f"the route at the speeds given, and leave at its last point; both ends should sit on a *spawn wall* — "
      f"an end cap (the water's edge at the world box) or a **berth**, a slip cut into the shoreline polygon "
      f"— so a vessel is never seen appearing on open water. A *closed* lane's vessels circulate, spaced "
      f"equally in time (no `headway_s`). Every pose is a pure function of time, so a run is reproducible "
      f"and a vessel never reacts to you. `waypoints`: {WP_MIN}–{WP_MAX}, legs {LEG_MIN:g}–{LEG_MAX:g} m, "
      f"intermediate radius {RADIUS_INTERMEDIATE:g} m and the goal {RADIUS_GOAL:g} m.")
    a("")
    a("**What `usvnav validate FILE` (and the studio, on every save) checks about lanes** — each problem "
      "names its rule (below) and says what to change:")
    a("")
    a(f"- L1 the corridor (the widest vessel plus {LANE_CLEAR:g} m each side) is clear of bodies and of the shore;")
    a(f"- L2 speeds within {TRAFFIC_SPEED_MIN:g}–{TRAFFIC_SPEED_MAX:g} m/s, acceleration between points at most {A_MAX:g} m/s²;")
    a(f"- L3/L4 the spacing guarantee: at the speed where your route meets the lane, `headway · v − L ≥ {EGO_SLOT:g} m` "
      f"(room for the hull between two vessels), and at every passage too narrow to pass beside a vessel the headway "
      f"leaves time to get through at {V_WAIT:g} m/s — so a lane can always be crossed by waiting for the gap;")
    a("- L5 lanes do not touch each other; L7 the corridor keeps out of the start pose and the goal's disc; "
      f"L8 no lane vessel within {SENSING_RANGE:g} m of the start at t = 0;")
    a(f"- L9 vessels {l_lo:g}–{l_hi:g} m × {w_lo:g}–{w_hi:g} m and a metre narrower than the lane's tightest passage; "
      f"L11 no turn over {LANE_TURN_MAX_DEG:g}° at a route point (insert points to round a corner); "
      "L10 (a warning) an open lane that does not end on a spawn wall.")
    a("")
    a("Static bodies follow the sizes in §5.1, keep off the start pose and every arrival disc, and must leave the "
      "route connected through free water for the hull. The other rules are named by what they check: `shoreline` "
      "(the boundary is a simple polygon), `reach` (the navigable area stays inside the world box; a warning), "
      "`terrain` (a file's terrain extent covers the raster's reach), `start` (the start pose is inside the "
      "boundary and touches nothing), `waypoints` (their count and leg lengths), `radius` (the arrival radii; a "
      "warning), `keep-clear` (no body inside the start pose or an arrival disc), `size` (body sizes per class; "
      "a warning), `connected` (each leg is passable through free water), and `traffic` / `traffic-speed` for "
      "legacy loops. The editor's own checks are the subset that needs no free-space grid; the "
      "studio's save and `usvnav validate` run the whole list.")


# --------------------------------------------------------------------------- RULES.md

def rules_md() -> str:
    budget_ms = 1000.0 * EPISODE_TIME_LIMIT_S / TICK_LIMIT
    static_names = {BUOY: "buoys", PIER: "piers", MOORED: "moored vessels", DOCK: "docks"}
    static_list = ", ".join(static_names[c] for c in STATIC_CLASSES[:-1]) + " and " + static_names[STATIC_CLASSES[-1]]
    n_words = {3: "three", 4: "four", 5: "five", 6: "six"}
    L = []
    a = L.append
    a("# Track 1 — the task, the interface and how the kit runs a submission")
    a("")
    a(STAMP)
    a("")
    a(f"{SITE_RULES} This document describes the kit: what an agent has to handle, the "
      "interface, and what the kit's own code does and enforces when it runs a submission.")
    a("")
    a("## 1. What an agent has to handle")
    a("")
    a("The capabilities below are the problem definition, in the kit's numbers; the courses "
      "you test against are the ones you author in the studio (`usvnav studio`). "
      "A solution should be able to:")
    a("")
    caps = (
        f"**Follow a route.** Reach {WP_MIN}–{WP_MAX} waypoints in order along a river reach, on legs of "
        f"{LEG_MIN:g}–{LEG_MAX:g} m — across the width, and out and back with the goal beside the start — "
        f"arriving within {RADIUS_INTERMEDIATE:g} m of each intermediate waypoint and within {RADIUS_GOAL:g} m of the "
        "goal, measured to the hull centre — without any part of the hull crossing the shoreline.",
        f"**Keep clear of static bodies** of {n_words.get(len(STATIC_CLASSES), len(STATIC_CLASSES))} classes — "
        f"{static_list} — with their true footprints, from a {SIZE_RANGES[BUOY][0]:g} m buoy to a "
        f"{SIZE_RANGES[MOORED][0][1]:g} m moored vessel, and choose how much clearance to trade for "
        "directness.",
        f"**Pass narrow gaps.** No passage on a hidden route is narrower than "
        f"{2.0 * plant.HULL_WIDTH:g} m, two hull widths, and passages down to that width occur.",
        "**Choose between routes** when the direct way is tight and an indirect way is open, "
        "including when the far side of a gap is not visible from its entrance.",
        f"**Predict and avoid moving vessels** that run on lanes between berths and end caps, on a "
        f"schedule, at {TRAFFIC_SPEED_MIN:g}–{TRAFFIC_SPEED_MAX:g} m/s, and never give way to you — "
        f"crossing a lane means waiting for the gap between two vessels; under 1-2, 1-3 "
        f"and 1-4 the observation carries no velocity and no identity, so their motion has to be "
        f"recovered from consecutive observations.",
        "**Slow down, stop and wait** when the water ahead is not clear, and get going again.",
        f"**Reverse** (down to {plant.V_MIN:g} m/s) out of a bad commitment — a dead end, an "
        f"over-run approach.",
        "**Turn where the straight line between consecutive waypoints crosses the bank:** the "
        "chain is a route through the channel, not a set of straight legs.",
        f"**Dock:** finish within {RADIUS_GOAL:g} m of a goal that sits beside a dock structure without touching it.",
        f"**Compensate a drift** under 1-4: a slowly varying lateral drift of up to "
        f"{plant.OUDisturbance.CAP} m/s, observable only as the mismatch between heading and "
        f"course (`vel[1]`) beyond the hull's own slip in turns, to be estimated and corrected online.",
        "**Do all of it from each of the four observation types with one agent,** within the "
        "runner's time limits (§4), deterministically — the same episode driven twice must give the same run.",
    )
    for k, c in enumerate(caps, 1):
        a(f"{k}. {c}")
    a("")
    a("## 2. The interface")
    a("")
    a("`Agent(config_path)` at construction, `reset(meta)` at episode start, "
      "`act(obs) -> [v_cmd, w_cmd]` every tick. `config_path` is the absolute path of a "
      "file inside your submission. No state may carry across episodes: a re-run of any "
      "single episode must reproduce its trace. The schema is `docs/OBSERVATION.md`.")
    a("")
    a("## 3. The submission")
    a("")
    a(f"A **directory** — see `docs/PACKAGING.md`: the agent module, its config, weights if "
      f"any, and a `{MANIFEST}` manifest, under {SIZE_CAP_BYTES // 2**20} MB. "
      f"`usvnav validate-submission DIR` applies every check mechanically; "
      f"a submission it rejects is not run.")
    a("")
    a("## 4. How a submission is executed")
    a("")
    a("- **The agent runs in a child process of the runner.** Only the observation and the "
      "action cross the boundary; simulator internals — the course, traffic futures, the "
      "disturbance — are not reachable from it.")
    a("- **No network, nothing outside the submission.** On the scoring machine the agent's "
      "process runs in a private filesystem that holds only the interpreter, `usvnav`, your "
      "submission (read-only) and a scratch directory, with no network; reading outside the "
      "submitted directory is prohibited. Anything the agent loads is inside the directory.")
    a("- **One agent process per condition**, constructed once and running that condition's "
      "episodes in sequence with `reset()` between them. What you load at construction is loaded "
      "four times per submission (again whenever a process is started again), not once per episode. "
      "The scoring machine and its packages are in `docs/RUNTIME.md`.")
    a(f"- **The runner's time limits.** Each episode must finish within **{EPISODE_TIME_LIMIT_S:.0f} s** "
      f"of wall-clock time, measured from the `reset(meta)` call to the end of the episode — your "
      f"agent's time and the scorer's together. An episode that exceeds it is stopped and recorded as "
      f"`time_overrun` (a submission fault), and your agent's process is started again for "
      f"the next episode. `Agent(config_path)` must construct within **{CONSTRUCT_TIMEOUT_S:.0f} s**, "
      f"or every remaining episode of that condition is `time_overrun`. The scoring sandbox also "
      f"limits your agent process's memory; that limit is not enforced by the kit and is stated on "
      f"the problem page.")
    a(f"- **Not real time, but timed.** The runner blocks on `act()`; 10 Hz is "
      f"simulated time, and there is no per-tick limit — a slow tick only spends the episode's "
      f"budget. The budget is per episode: an episode that runs to the {TICK_LIMIT}-tick limit has "
      f"**{budget_ms:.0f} ms per tick** on average for your agent and the scorer together, of which "
      f"the scorer's own work is about 1–2 ms. Time your agent's `act()` — `usvnav validate-submission` "
      f"reports it — rather than a whole local run: the kit draws the 1-2 / 1-4 picture in pure "
      f"Python, which is slower than the scoring machine's renderer (the pictures are identical), so "
      f"on your own machine `usvnav leaderboard submit` can stop a long 1-2 / 1-4 episode that the "
      f"scoring machine finishes (`--episode-limit-s` raises the limit there).")
    a(f"- **Episode end.** {TICK_LIMIT} ticks per episode. "
      f"Outcomes: {', '.join(f'`{o}`' for o in NAVIGATIONAL)} are navigational; "
      f"{', '.join(f'`{o}`' for o in SUBMISSION_FAULT)} are submission faults "
      f"(`docs/OBSERVATION.md` §6).")
    a("")
    a("## 5. The courses")
    a("")
    a("`sets/practice/` holds a few composite courses of low-to-medium difficulty: enough to "
      "see the format and run the tooling, not a sample of the hidden set. You are expected "
      "to imagine the hard cases yourself and build them in the editor. **Every hidden course "
      "passes the same course-file rules** the studio and `usvnav validate` apply. **No competent "
      "agent is distributed**, and the shipped tutorial agent usually "
      "fails a course — so to confirm your setup, author an easy course "
      "in the studio. The generator that draws the hidden courses is an organiser tool and is "
      "not in the kit. Hidden episodes run through the simulator shipped to you; the scoring machine "
      "produces byte-identical observations.")
    return "\n".join(L)


# --------------------------------------------------------------------------- RUNTIME.md

def runtime_md() -> str:
    R = runtime.RUNTIME
    L = ["# Track 1 — the scoring runtime", "", STAMP, "",
         f"What a submission meets at scoring time, identified as `{R['id']}` — the value "
         f"the manifest's `runtime` field must carry.", ""]
    cuda = ", ".join(f"`{k}=={v}`" for k, v in R["cuda"].items())
    L += _table(("what", "value"), [
        ("Python", f"{R['python']} (major.minor pinned; the patch level is not)"),
        *[(f"`{k}`", f"{v}, pinned exactly") for k, v in R["packages"].items()],
        ("CUDA libraries", f"the pip packages onnxruntime-gpu loads, pinned exactly: {cuda}"),
        ("execution providers", ", ".join(f"`{p}`" for p in R["providers"])),
        ("other packages", "the runtime's own packages — the standard library, numpy, onnxruntime "
                           "and `usvnav` — may be imported; anything else your agent imports must be "
                           "inside your submission directory, as pure Python or as wheels built for "
                           "Linux x86_64 / CPython 3.13 (compiled extensions included) unpacked there"),
        ("network", "none"),
        ("CPU", R["cpu"]),
        ("RAM", R["ram"]),
        ("GPU", R["gpu"]),
        ("sharing", R["sharing"]),
        ("memory limit", "set by the scoring sandbox, not by the kit; see the problem page"),
        ("time limits", f"{EPISODE_TIME_LIMIT_S:.0f} s of wall clock per episode, from the `reset(meta)` "
                        f"call to the end of the episode, the agent's time and the scorer's together "
                        f"(exceeded: that episode is `time_overrun`, and the agent's process is started "
                        f"again for the next episode); `Agent(config_path)` within "
                        f"{CONSTRUCT_TIMEOUT_S:.0f} s"),
        ("submission form", R["submission_form"]),
        ("agent process", R["agent_process"]),
        ("wall clock", R["wall_clock"]),
    ])
    ort = R["packages"]["onnxruntime-gpu"]
    np_ver = R["packages"]["numpy"]
    pins = " ".join(f"{k}=={v}" for k, v in R["cuda"].items())
    L += ["",
          "The interpreter and the package set do not change during the contest. The shipped "
          "`usvnav` package depends on numpy and nothing else: everything the scorer runs has "
          "to exist on a machine with no network. How the runner applies the time limits is in "
          "`docs/RULES.md` §4. " + SITE_RULES,
          "",
          "## onnxruntime",
          "",
          "The runtime provides `onnxruntime`, GPU build, so a learned component has "
          "one framework-neutral way to run: export to ONNX from PyTorch, TensorFlow or JAX, "
          "ship the `.onnx` file inside your submission, and open it with "
          "`onnxruntime.InferenceSession(path, providers=[\"CUDAExecutionProvider\", "
          "\"CPUExecutionProvider\"])`. It is the same version Track 3 pins, installed once on the "
          "scoring machine; nothing else about it is configured (default session options, no "
          "TensorRT). The CUDA provider is a pure win only for a model large enough to amortise "
          "the copy; a small network is often faster on the CPU provider, and the wall clock per "
          "tick counts against the time limits either way.",
          "",
          "To match it locally — the interpreter and numpy too, not only onnxruntime: the kit "
          f"installs on any Python from 3.10 and any numpy from 1.24, but the scorer runs Python "
          f"{R['python']} and numpy {np_ver}, and numpy 1.x and 2.x differ in type promotion and "
          "copy semantics, so develop on the scorer's versions:",
          "",
          "```",
          f"python --version                        # {R['python']}.x, the scorer's interpreter",
          f"pip install numpy=={np_ver}",
          f"pip install onnxruntime-gpu=={ort} {pins}",
          f"pip install onnxruntime=={ort}          # CPU build: same API, same numbers to float precision, "
          "no card needed",
          "```",
          "",
          "The GPU build finds its CUDA libraries in those pip packages; no system CUDA install "
          "is needed or used."]
    return "\n".join(L)


# --------------------------------------------------------------------------- PACKAGING.md

def packaging_md() -> str:
    L = ["# Track 1 — submission packaging", "", STAMP, "",
         "A submission is a **directory**. What is in it, as files:", "",
         "```",
         "my-submission/",
         f"  {MANIFEST}     the manifest (below)",
         "  agent.py            exposes `Agent(config_path)` -- the interface",
         "  config.json         anything you like; its absolute path is what `Agent()` receives",
         "  weights/ ...        optional; no network at scoring time, so anything you load is here",
         "```", "",
         f"## The manifest, `{MANIFEST}`", "",
         "```json", json.dumps({"format": FORMAT, "entry": "agent:Agent",
                                "config": "config.json", "runtime": runtime.RUNTIME_ID}, indent=1),
         "```", ""]
    L += _table(("key", "meaning"), [
        ("`format`", f"`{FORMAT}`"),
        ("`entry`", "`module:Class`; the module is a `.py` file or a package inside the directory"),
        ("`config`", "a path inside the directory; passed to `Agent()` as an absolute path"),
        ("`runtime`", f"the runtime you expect: `{runtime.RUNTIME_ID}` (`docs/RUNTIME.md`)"),
    ])
    L += ["", f"All {len(REQUIRED)} keys are required. The manifest carries no name: the contest identifies a "
          "submission by the submission ID it is uploaded with, and a local board names its row after "
          "the submission's directory.", "",
          "## The local validator", "",
          "```", "usvnav validate-submission my-submission/", "```", "",
          "Every requirement is mechanically checkable, and the validator checks every one, "
          "each as a line of its report. The static checks run first; if they "
          "pass, a **smoke run** constructs your agent in a child process, calls `reset` with "
          "a real course's metadata and drives it for a few hundred ticks under each condition "
          "through the same `run_episode` the scorer uses — so an interface mistake cannot pass "
          "here and fail there. The tutorial agent passes; the validator says nothing about "
          "whether an agent is any good.", ""]
    L += _table(("check", "what passes"), [(f"`{c}`", what) for c, what in CHECKS])
    L += ["", "A submission the validator rejects is not run and not stored by the leaderboard. "
          "`--out report.json` writes the full report; `--conditions 1-1,1-3 --ticks 60` makes "
          "a quick pass while iterating.", "",
          "## The worked example", "",
          "`examples/submission/` is a complete, valid submission: a pure-pursuit follower that "
          "reads the perception field of each condition and slows when something is close "
          "ahead. Copy it and replace `agent.py`. It is "
          "tutorial-grade on purpose — it completes open reaches and little else."]
    return "\n".join(L)


# --------------------------------------------------------------------------- build

def build(out: pathlib.Path | None = None) -> dict:
    """Return `{relative path: bytes}` of every generated file."""
    course = _course()
    captures = {c: capture(course, c) for c in CONDITIONS}
    files: dict[str, bytes] = {}

    files["OBSERVATION.md"] = (observation_md(course, captures) + "\n").encode()
    files["RULES.md"] = (rules_md() + "\n").encode()
    files["RUNTIME.md"] = (runtime_md() + "\n").encode()
    files["PACKAGING.md"] = (packaging_md() + "\n").encode()

    import io
    import tempfile
    with tempfile.TemporaryDirectory() as tmp:
        p = pathlib.Path(tmp) / "course.json"
        coursefile.save(course, p)
        files["examples/course.json"] = p.read_bytes()
        meta = captures["1-1"][0]
        files["examples/meta.json"] = (json.dumps(_listify(dict(meta)), indent=1) + "\n").encode()
        for cond in CONDITIONS:
            _, obs = captures[cond]
            common = {k: _listify(v) for k, v in obs.items() if k != "perception"}
            per = obs["perception"]
            if cond == "1-1":
                common["perception"] = _listify(per)
            elif cond == "1-3":
                common["perception"] = _listify(per)
            else:
                png = pathlib.Path(tmp) / f"{cond}.png"
                write_png(png, per)
                files[f"examples/observation-{cond}.png"] = png.read_bytes()
                if cond == "1-2":
                    write_png(png, per, scale=3)
                    files["examples/observation-1-2-x3.png"] = png.read_bytes()
                flat = per.reshape(-1, 3)
                counts = {name: int(np.all(flat == np.array(rgb, dtype=np.uint8), axis=1).sum())
                          for name, rgb in PALETTE_TRACK1.items()}
                common["perception"] = {"file": f"observation-{cond}.png",
                                        "shape": list(per.shape), "dtype": str(per.dtype),
                                        "exact_colour_pixels": counts,
                                        "boundary_pixels": int(len(flat) - sum(counts.values()))}
            files[f"examples/observation-{cond}.json"] = (json.dumps(common, indent=1) + "\n").encode()
    if out is not None:
        for rel, data in files.items():
            path = pathlib.Path(out) / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    return files


def check(out: pathlib.Path = DOCS) -> list[str]:
    """Which generated files differ from (or are missing in) `out`."""
    files = build(None)
    bad = []
    for rel, data in files.items():
        path = pathlib.Path(out) / rel
        if not path.is_file() or path.read_bytes() != data:
            bad.append(rel)
    return bad


def cmd_docs(args) -> int:
    out = pathlib.Path(args.out) if args.out else DOCS
    if args.check:
        bad = check(out)
        for rel in bad:
            print(f"  [stale ] {rel}")
        print("docs match the code" if not bad else f"{len(bad)} file(s) differ; run `usvnav docs`")
        return 1 if bad else 0
    files = build(out)
    for rel in files:
        print(f"  wrote {out / rel}")
    return 0
